### ISSUE TITLE
Wrong Session API Location

### ISSUE THREAD

**Issue by avatarworf** [Financial-Times/spoor-enrichment#103]
You should be using sessionapi.memb.ft.com instead of sessionapi-glb.memb.ft.com to access the session API as per API docs

https://github.com/Financial-Times/spoor-enrichment/blob/master/server/transforms/sessionApi.js#L36

Any Plans to allow  ENV=test to access the sessionapi-test.memb.ft.com endpoint?

**Comment by commuterjoy** [comment]
ooops, thanks - https://github.com/Financial-Times/spoor-enrichment/pull/108
