### ISSUE TITLE
B2C/B2B flag and B2B account

### ISSUE THREAD

**Issue by markstephens** [Financial-Times/spoor-enrichment#110]
More info to come from this API:

https://sites.google.com/a/ft.com/technology/systems/membership/identity-and-access-management/02-sub-systems/access-licence-service

http://git.svc.ft.com/projects/OM/repos/acc-licence-svc/browse/acc-licence-svc/src/main/resources/web/api.raml

**Comment by commuterjoy** [comment]
AFAIK we need to wait till they are the other side of the firewall.

**Comment by commuterjoy** [comment]
shipped
