### ISSUE TITLE
Identify staff from inside the FT's offices

### ISSUE THREAD

**Issue by commuterjoy** [Financial-Times/spoor-enrichment#120]
ip address I assume

**Comment by commuterjoy** [comment]
@markstephens fancy finding some ip address details?

**Comment by markstephens** [comment]
I've emailed them to you, not sure if I should just post them on t'internet.

**Comment by commuterjoy** [comment]
thanks, it's a public github project :)

**Comment by commuterjoy** [comment]
We could add this to the MaxMind API?

**Comment by georgecrawford** [comment]
A membership lookup would also be good, for known users.

**Comment by commuterjoy** [comment]
done in maxmind
