### ISSUE TITLE
Sanitise device versions from Device Atlas

### ISSUE THREAD

**Issue by georgecrawford** [Financial-Times/spoor-enrichment#134]
Our iOS device versions, for example, look like this: `9_1`, `9_0_2`, `9_0_1`, `9_0`, `8_4_1` by the time they get to Redshift. It'd be awesome to sanitise those to a semver-esque form (`9.1.0`, `9.0.0`, etc.), and also to add `device-major-version`, `device-minor-version`, `device-patch-version`, etc.

**Comment by commuterjoy** [comment]
Can we get away with a `"9_0_2".replace(/_/g, '.')` over the versions?

**Comment by georgecrawford** [comment]
It'd be a help, but ideally we'd zero-fill the missing minor/patch fields, and also add separate fields for major/minor/patch version. I'd like to easily be able to chart the breakdown of iOS9 minor versions, for example.  


George

________________


George Crawford
Senior Developer, Financial Times

+44 (0)752 567 9717
Number One Southwark Bridge,
London SE1 9HL

> On 6 Oct 2015, at 18:43, Matt Chadburn <notifications@github.com> wrote:
> 
> Can we get away with a "9_0_2".replace(/_/g, '.') over the versions?
> 
> —
> Reply to this email directly or view it on GitHub.
> 

-- 

------------------------------
This email was sent by a company owned by Pearson plc, registered office at 
80 Strand, London WC2R 0RL.  Registered in England and Wales with company 
number 53723.

**Comment by commuterjoy** [comment]
Something like this ?

```js
let s = "9_0_2".split('_')
let [maj, min, patch] = s;
let semver = [maj, min, patch].join('.') + ( s.length > 3 ? `+${s.slice(3).join('_')}` : '' )
let tokens = { major: parseInt(maj) ... } 
```

yields - `9.0.2` or if there's stuff after the third token `9.0.2+143`

**Comment by georgecrawford** [comment]
Yep, that looks perfect. Also gives `{"major":9,"minor":1,"patch":null}` for `9.1`, for example, which will do fine. Thanks Matt.

**Comment by commuterjoy** [comment]
What would you do with `46.0.2490.76` from Chrome ?

**Comment by georgecrawford** [comment]
I'd suggest just assuming major/minor/patch and discarding any further chunks, rather than trying to get this perfect for all UA version strings. The complete version will still be available, and if further detail is required we can add it case-by-case.

**Comment by commuterjoy** [comment]
@markstephens says, 

I’m planning to change device atlas to give the major and minor versions, instead of 

`browserVersion:"47.0.2526.106"`

it would now be

`browserVersion = {"version":"47.0.2526.106","major":"47","minor":"0"}`

**Comment by markstephens** [comment]
Ah, forgot about this thread
- should I add patch to my object?
- And parseInt?

I'm using this code to get the major and minor:
```js
var version_re = /(\d+)\D*(\d*)/;

// Tests - looking for items 2 and 3 in each result
'47.0.2526.106'.match(version_re) // ["47.0", "47", "0"]
"9_0_2".match(version_re) // ["9_0", "9", "0"]
'47'.match(version_re) // ["47", "47", ""]
'NT 6.1'.match(version_re) // ["6.1", "6", "1"]
```

**Comment by commuterjoy** [comment]
> should I add patch to my object?

No, I don't think so. I think most vendors don't really do semver, so major and minor is fine. 

> parseInt

Yes. I think the integers will be more useful when querying.

**Comment by markstephens** [comment]
ok, this is done.

**Comment by commuterjoy** [comment]
@georgecrawford Happy to close? If not, reopen?

**Comment by georgecrawford** [comment]
:+1:
