### ISSUE TITLE
New enrichment - Traffic source

### ISSUE THREAD

**Issue by markstephens** [Financial-Times/spoor-enrichment#176]
Attraction type is calculated from 3 fields:

1. segmentid parameter (in the url, but needs to be looked up from an API)
2. ftcamp parameter (in the url)
3. referrer type (already calculated from another enrichment)

They should be taken in the order above e.g. segment id is highest priority, then ftcamp and falling back to referrer type. The first one that matches and returns successfully should be the result of this enrichment .

### segment id
- Will be a parameter in the URL
- It needs to be looked up against a segment api (membership) as there are 2 types of segment id - internal and external
    - Incidentally, we need this internal/external flag in redshift too (as well as the segment name), so it should/could be a separate enrichment.
- If it's an internal segment id, it should be ignored for this calculation

### ftcamp
- Parameter in the url
- ftcamps are slash delimited e.g. `part 1/part-2/part_3/part4/part 5/part6`
- If it exists, then the first part should be returned

### referrer type
- Fallback to the referrer type calculated in https://github.com/Financial-Times/spoor-enrichment/blob/master/server/transforms/referrer-api.js#L37

**Comment by commuterjoy** [comment]
> but needs to be looked up from an API 

which one?

**Comment by markstephens** [comment]
I'm asking, added you on an email.

**Comment by markstephens** [comment]
(Copying from email thread)

We've found an API from membership's test environment:
http://offerapi-test.memb.ft.com:8080/membership/offers/v1?segmentId=fc362216-7cb7-97f5-988f-794d727b5537

And an API that lists segment metadata
http://offerapi-test.memb.ft.com:8080/membership/segments/v1

(Looks like they're internal only, maybe the prod versions are better)

**Comment by markstephens** [comment]
The plan is to use the following logic:

1. If segment ID is found and is external, use source
2. If not, use SegID, if one is found - convert it to a Segment ID using API and check is external
3. If not, use FTCAMP if one is found - use the first slice in the camp.
4. If not, use referrer information - referrer type.

We're planning to create an API off of Redshift for all the data. We have it and think it will be a quicker route to market.

**Comment by markstephens** [comment]
@akilananb
(cc @commuterjoy)

Can you start on this one now. I think we have everything.

The segment API is:
http://segment-metadata-api-540345386.eu-west-1.elb.amazonaws.com/segmentmetadata?segmentId=34f63f07-9653-9a35-a02c-e3112a389ea2
The SegID API is:
http://segment-metadata-api-540345386.eu-west-1.elb.amazonaws.com/segmentmetadata?segId=400870

The internal/external parameter will be shown in the purpose field, just need the data to get updated with Bastien's updates - which is happening/happened.

**Comment by akilananb** [comment]
@markstephens  Sure i'll look into that.

**Comment by markstephens** [comment]
Hi @akilananb 

The enrichment should return three fields:

```json
{
    "type" : "",
    "name" : "",
    "external" : ""
}
```

**type**
- When it's a segment or seg ID, use `channel` from the API response.
- When it's an ftcamp, split on `/` and use the first element.

**name**
- When it's a segment or seg ID, use `name` from the API response.
- When it's an ftcamp, split on `/` and use the last element. (e.g. `slice(-1)[0]`)

**external**
- Will be `true` when it's a segment, seg id or ftcamp.
- `false` when it falls back to the referrer.

**Comment by akilananb** [comment]
@markstephens Thanks for the information. What would be type and name it falls back to referrer

**Comment by markstephens** [comment]
The referrer enrichment already has a type and name, so re-use those.

**Comment by akilananb** [comment]
@markstephens Oh k thanks

**Comment by commuterjoy** [comment]
done? File a new ticket for any bugs.
