### ISSUE TITLE
Validate event categories and actions

### ISSUE THREAD

**Issue by commuterjoy** [Financial-Times/spoor-enrichment#177]
- Keep a list of known/acceptable categories and actions in a dictionary somewhere.
- Add a filter to the pipeline to check incoming events are known.
- Make sure sender on unknown events knows that invalid events are not acceptable.

related: https://github.com/Financial-Times/spoor-api/issues/2

**Comment by adambraimbridge** [comment]
@commuterjoy At the moment, we're validating that an event must have an action and a category. But we're not keeping a list of acceptable values.
