### ISSUE TITLE
FT region is poorly

### ISSUE THREAD

**Issue by markstephens** [Financial-Times/spoor-enrichment#192]
We have completely the wrong list.

This is the correct official list: https://drive.google.com/a/ft.com/file/d/0B0Jd9EQyZFcQc3cxRWstTGpBVGc/view?usp=sharing
We would want to return the "High level" column.

Quickest fix - update your map in utils with this.
Longer fix - turn into an API?

**Comment by commuterjoy** [comment]
> Quickest fix - update your map in utils with this.

ok - @akilananb do you want to pick this up?

> Longer fix - turn into an API?

if if changes often, yeah.

**Comment by akilananb** [comment]
Ya sure i'll look into it.
For Longer Fix
Is already ftregion api has been built or we have create one...?

**Comment by markstephens** [comment]
I think we would need to create one, I asked the DSG (data standards group) and they don't have one. 

But as Matt hinted at, it probably doesn't change often. 



> On 21 Jan 2016, at 08:18, Akilan Anbu <notifications@github.com> wrote:
> 
> Ya sure i'll look into it.
> For Longer Fix
> Is already ftregion api has been built or we have create one...?
> 
> —
> Reply to this email directly or view it on GitHub.
> 

-- 

------------------------------

*This email was sent by a company owned by Financial Times Group Limited 
("FT Group <http://aboutus.ft.com/corporate-information/#axzz3rajCSIAt>"), 
registered office at Number One Southwark Bridge, London SE1 9HL.  
Registered in England and Wales with company number 879531. This e-mail may 
contain confidential information. If you are not the intended recipient, 
please notify the sender immediately, delete all copies and do not 
distribute it further.  It could also contain personal views which are not 
necessarily those of the FT Group.  We may monitor outgoing or 
incoming emails as permitted by law.*

**Comment by commuterjoy** [comment]
done?
