### ISSUE TITLE
Don't classify email events as bot traffic

### ISSUE THREAD

**Issue by commuterjoy** [Financial-Times/spoor-enrichment#212]
i.e. avoid maxmind classification.

/cc @richard-still-ft

**Comment by markstephens** [comment]
- It’s the device atlas api, not the maxmind api
- I was thinking it would be better to make a change in the device atlas api, so it’s closer to the source of truth (e.g. all device stuff and odd additions is all contained in the device api)
- For that to work, they’d have to send me a custom user-agent
- This applies to more than just email events, so a central change would be better.

**Comment by commuterjoy** [comment]
done in http://git.svc.ft.com:8080/projects/DW/repos/device-atlas-service/pull-requests/8/overview
