### ISSUE TITLE
Normalize referrer subdomains (specifically 'www')

### ISSUE THREAD

**Issue by adambraimbridge** [Financial-Times/spoor-enrichment#218]
![image](https://cloud.githubusercontent.com/assets/224547/12726269/a9e7ef06-c90e-11e5-824a-e1c0ba189293.png)

Example: https://beacon.ft.com/graph/anons/visitors
— drudgereport.com and www.drudgereport.com should be considered the same for the purposes of this chart.

Possible file to update: https://github.com/Financial-Times/spoor-enrichment/blob/master/server/transforms/referrer-api.js

**Comment by commuterjoy** [comment]
Perhaps need to add an extra field in the [referrer spreadsheet](https://bertha.ig.ft.com/republish/publish/gss/1j1eiv5XkaqKSLCET7BWydydM7kX8nS-VLZKcFWmFB-s/referrers)?

I can't think of a simple way to parse the hostname and figure out what's a subdomain, tld etc.

**Comment by markstephens** [comment]
agree with Matt, isn't the referrer.name enrichment good enough already?

**Comment by commuterjoy** [comment]
@adambraimbridge my only thought here is that we could trim the list of [TLDs](https://en.wikipedia.org/wiki/List_of_Internet_top-level_domains) from the host name than split by `.` and take the last item from the array.

```
www.bbc.co.uk -> bbc
www.bbc.com -> bbc
mobile.news.reith.bbc.co.uk -> bbc
```

**Comment by markstephens** [comment]
I like the idea to add more entries to referrers spreadsheet. It's aim is basically to do this.

**Comment by adambraimbridge** [comment]
I don't have any opinion really. I like @wheresrhys' approach in https://github.com/Financial-Times/spoor-enrichment/issues/253

**Comment by adambraimbridge** [comment]
I theory we could do custom normalisation per dashboard, but I think everyone agrees it's better to do that at the enrichment stage

**Comment by adambraimbridge** [comment]
I didn't know about that referrers spreadsheet — looks like the solution

**Comment by chrisbrownuk** [comment]
The referrers' spreadsheet does give full control to how the referrers are
classified and is easy for Analytics, etc, to adjust the classifications in
future. However it does not give a generic solution as discussed earlier to
trim off the TLD and subdomains from the domain name.

If this is sufficient for the common referrers (e.g. google and bbc are
already there) then that's great.

Note that I changed the Regexs recently as they were matching substrings
within the referrer hostname.  The original iJento set used Java not
JavaScript to perform full string matches, so didn't need all the carets
and dollars.

-- 

*Chris Brown*
TPO Web Analytics
Data Technology
Financial Times, One Southwark Bridge, London SE1 9HL

chris.brown@ft.com | +44 (0)207 873 4701

------------------------------

On 1 March 2016 at 14:52, Adam Braimbridge <notifications@github.com> wrote:

> I didn't know about that referrers spreadsheet — looks like the solution
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Financial-Times/spoor-enrichment/issues/218#issuecomment-190754534>
> .
>

-- 

------------------------------

*This email was sent by a company owned by Financial Times Group Limited 
("FT Group <http://aboutus.ft.com/corporate-information/#axzz3rajCSIAt>"), 
registered office at Number One Southwark Bridge, London SE1 9HL.  
Registered in England and Wales with company number 879531. This e-mail may 
contain confidential information. If you are not the intended recipient, 
please notify the sender immediately, delete all copies and do not 
distribute it further.  It could also contain personal views which are not 
necessarily those of the FT Group.  We may monitor outgoing or 
incoming emails as permitted by law.*

**Comment by wheresrhys** [comment]
I think our problem is that in beacon-v2 we're not allowing this referrer.name thing through. At least I don't think we are

**Comment by wheresrhys** [comment]
Turns out we were all along. `page:view->count()->group(page.referrer.name)->filter(page.referrer.name!~FT)->sortDesc()->print(Table)` gives us a pretty good result

**Comment by commuterjoy** [comment]
Decision - Moved to https://github.com/Financial-Times/spoor-website-type/issues/6
