### ISSUE TITLE
Counted content

### ISSUE THREAD

**Issue by markstephens** [Financial-Times/spoor-enrichment#221]
Can you adjust the counted content logic to take into account more brands as they don't follow the same pattern as ft.com articles.

This is important as we're under-counting at the mo, and it's affecting the models such as rfv and others.

The brands are:

- /fastft
- /presscuttings/s/3/
- /the-a-list/
- /brusselsblog/
- /businessblog/
- /david-allen-green/
- /ftdata/
- /material-world/
- /off-message/
- /the-world/
- /westminster/
- /lex-live/

Thanks

**Comment by markstephens** [comment]
@akilananb

**Comment by commuterjoy** [comment]
```

**Comment by akilananb** [comment]
@commuterjoy  You mean like instead of validating for above mentioned brand juz make it counted if it has brand in it...?

**Comment by markstephens** [comment]
I don't think every brand will be counted. 

You need to look for those brands. 




> On 11 Feb 2016, at 06:15, Akilan Anbu <notifications@github.com> wrote:
> 
> @commuterjoy You mean like instead of validating for above mentioned brand juz make it counted if it has brand in it...?
> 
> —
> Reply to this email directly or view it on GitHub.
> 

-- 

------------------------------

*This email was sent by a company owned by Financial Times Group Limited 
("FT Group <http://aboutus.ft.com/corporate-information/#axzz3rajCSIAt>"), 
registered office at Number One Southwark Bridge, London SE1 9HL.  
Registered in England and Wales with company number 879531. This e-mail may 
contain confidential information. If you are not the intended recipient, 
please notify the sender immediately, delete all copies and do not 
distribute it further.  It could also contain personal views which are not 
necessarily those of the FT Group.  We may monitor outgoing or 
incoming emails as permitted by law.*

**Comment by akilananb** [comment]
@markstephens  Where can I find id for those brands...?

**Comment by commuterjoy** [comment]
I think this is done, but I want to migrate it to #245 ASAP
