### ISSUE TITLE
Referrer API bug

### ISSUE THREAD

**Issue by markstephens** [Financial-Times/spoor-enrichment#233]
Hi

This line is wrong: https://github.com/Financial-Times/spoor-enrichment/blob/master/server/transforms/referrer-api.js#L17

If there isn't a referrer, then it shouldn't fall back to the headers from the request made to spoor-api as these would _always_ be an ft.com domain - and therefore marked as internal which is wrong, it's allowed to be null.

@akilananb 
@commuterjoy

**Comment by commuterjoy** [comment]
shipped in #249, please reopen if that doesn't look good /cc
