### ISSUE TITLE
Is Staff?

### ISSUE THREAD

**Issue by markstephens** [Financial-Times/spoor-enrichment#238]
https://github.com/Financial-Times/spoor-enrichment/blob/master/server/transforms/is-staff.js

We're missing membership's automated testing, and I _think_ the best place to tag these, is as staff.

All their tests run as a a logged in user with the email address domain is ftqa.org

Simplest enhancement - with the enrichments in their current format - is to check cookies for ftqa.org in the is-staff enrichment.

Longer term, you might merge is-staff and user-api enrichments together, as the info will need to be looked up from user-api.

**Comment by commuterjoy** [comment]
Membership need to send the `spoor-test` header and the message will be dropped by the pipeline.

http://spoor-docs.herokuapp.com/usage#test-data

**Comment by markstephens** [comment]
Ah, that means I need a hook in o-tracking to add that header...

Is staff should change to user-api at some point.

**Comment by commuterjoy** [comment]
drops test events - https://github.com/Financial-Times/spoor-enrichment/pull/242

... which I realised I wasn't doing.

**Comment by commuterjoy** [comment]
I don't think there's any action for spoor here, as the API supports the `spoor-test` header for this purose
