### ISSUE TITLE
Traffic Source changes

### ISSUE THREAD

**Issue by chrisbrownuk** [Financial-Times/spoor-enrichment#248]
## Traffic source type 

1. Segment ID and Seg ID values should only be used if  "purpose" is "External" in the results from the API call.
2. needs to take the second slash-delimited token from ftcamp and not the first.
2. should default to 'direct' if no campaign (segment, segid or ftcamp) or referrer is present.
3. should be 'other campaign' if ftcamp does not have second slash-delimited token but is not null.

## Traffic source name 

1. Segment ID and Seg ID values should only be used if  "purpose" is "External" in the results from the API call.
1. needs to take the first slash delimited token from ftcamp and not the last.
2. should default to 'direct' if no campaign (segment, segid or ftcamp) or referrer is present.

## Referrer Type

1. If a referrer url exists but does not match a known host then it should default to 'other referrer' instead of remaining null.
3. Referrer type still coming through as internal for direct traffic, see other issue #233.

**Comment by chrisbrownuk** [comment]
Looking at the code after the latest changes, it looks like we will get "other" if the ftcamp doesn't have a slash in it, and get "unclassified" if it is an unknown referrer.

I did want traffic_source_type to be "other campaign" and "other referrer" respectively.  That way it would have been obvious what the source was.  It won't be clear to end users of reports what the difference is between "other" and "unclassified".

I'd be happy with referrer_type being "unclassified" provided this gets converted into "other referrer" or even "unclassified referrer" when setting traffic_source_type.  So I'm fine with spoor-website-type returning "unclassified" provided this can be translated when being used to set the traffic_source_type.

Thanks
Chris

**Comment by commuterjoy** [comment]
> I did want traffic_source_type to be "other campaign" and "other referrer" respectively.

ah, perhaps they should both be unclassified?

**Comment by chrisbrownuk** [comment]
"unclassified campaign" and "unclassified referrer" would be fine, if you
don't like other, but we do need to distinguish between the two.

-- 

*Chris Brown*
TPO Web Analytics
Data Technology
Financial Times, One Southwark Bridge, London SE1 9HL

chris.brown@ft.com | +44 (0)207 873 4701

------------------------------

On 25 February 2016 at 22:02, Matt Chadburn <notifications@github.com>
wrote:

> I did want traffic_source_type to be "other campaign" and "other referrer"
> respectively.
>
> ah, perhaps they should both be unclassified?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Financial-Times/spoor-enrichment/issues/248#issuecomment-189005572>
> .
>

-- 

------------------------------

*This email was sent by a company owned by Financial Times Group Limited 
("FT Group <http://aboutus.ft.com/corporate-information/#axzz3rajCSIAt>"), 
registered office at Number One Southwark Bridge, London SE1 9HL.  
Registered in England and Wales with company number 879531. This e-mail may 
contain confidential information. If you are not the intended recipient, 
please notify the sender immediately, delete all copies and do not 
distribute it further.  It could also contain personal views which are not 
necessarily those of the FT Group.  We may monitor outgoing or 
incoming emails as permitted by law.*

**Comment by commuterjoy** [comment]
@akilananb @chrisbrownuk can you reopen if not done?
