### ISSUE TITLE
is-staff is broken

### ISSUE THREAD

**Issue by commuterjoy** [Financial-Times/spoor-enrichment#252]
`server/transforms/is-staff.js`

Membership don't drop this cookie now, so this means of detection isn't going to work any more.

**Comment by laurieboyes** [comment]
I assume there's a reason this won't work but thought I'd float it anyway: Could we just identify staff members as anyone with an `ft.com` or `ftqa.org` email address?

**Comment by commuterjoy** [comment]
Yup, it would work for most people.

You could also use isFtOffice flag on the maxmind API too, which works today.

**Comment by commuterjoy** [comment]
fixing as part of #110
