### ISSUE TITLE
Traffic Source not set correctly for unclassified referrers

### ISSUE THREAD

**Issue by chrisbrownuk** [Financial-Times/spoor-enrichment#255]
Page views with no campaign and a referrer type of "unclassified referrer" are being assigned a traffic source type of "direct" and a traffic source name of "direct".  This is incorrect.  It should be assigned a traffic source type of "unclassified referrer" and a traffic source name set to the referrer hostname.

See also #248

**Comment by akilananb** [comment]
@chrisbrownuk  can we close this...?

**Comment by chrisbrownuk** [comment]
Yes

-- 

*Chris Brown*
TPO Web Analytics
Data Technology
Financial Times, One Southwark Bridge, London SE1 9HL

chris.brown@ft.com | +44 (0)207 873 4701

------------------------------

On 15 March 2016 at 08:38, Akilan Anbu <notifications@github.com> wrote:

> @chrisbrownuk <https://github.com/chrisbrownuk> can we close this...?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
>
> https://github.com/Financial-Times/spoor-enrichment/issues/255#issuecomment-196720074
>

-- 

------------------------------

*This email was sent by a company owned by Financial Times Group Limited 
("FT Group <http://aboutus.ft.com/corporate-information/#axzz3rajCSIAt>"), 
registered office at Number One Southwark Bridge, London SE1 9HL.  
Registered in England and Wales with company number 879531. This e-mail may 
contain confidential information. If you are not the intended recipient, 
please notify the sender immediately, delete all copies and do not 
distribute it further.  It could also contain personal views which are not 
necessarily those of the FT Group.  We may monitor outgoing or 
incoming emails as permitted by law.*
