### ISSUE TITLE
Safari Mobile - call it by it's real name

### ISSUE THREAD

**Issue by wheresrhys** [Financial-Times/spoor-enrichment#270]
device Atlas gives us browser: Safari and primaryDeviceType: Tablet or mobile.

Should we map this to 'Safari Mobile'? It's a different browser so it'd be helpful to distinguish by name

**Comment by commuterjoy** [comment]
Yes, but do it in the device atlas API (node app in Stash)

**Comment by wheresrhys** [comment]
http://git.svc.ft.com/projects/DW/repos/device-atlas-service/pull-requests/11/overview
