### ISSUE TITLE
Change anonymous propensity to use spoor-id

### ISSUE THREAD

**Issue by chrisbrownuk** [Financial-Times/spoor-enrichment#276]
We want to switch over to using spoor data for the anonymous propensity scores.  This will involve switching over from using the SIVISITOR cookie to the spoor-id both front-end and on what the API serves.  This will require these changes to be coordinated.

**Comment by commuterjoy** [comment]
Propensity API is disabled in spoor-enrichment while we make this change

**Comment by commuterjoy** [comment]
shipped :ship:
