### ISSUE TITLE
Support webhooks

### ISSUE THREAD

**Issue by commuterjoy** [Financial-Times/spoor-enrichment#277]
Webhooks (from circle, github, heroku, pingdom etc.) contain lots of useful information about what are systems are doing but their contents do not conform to the Spoor input format (Eg, omits _category_ and _action_)
 
Can we adapt these formats before they are transformed in to a minimal spoor-friendly format so they can be fed in to the analytics.

**Comment by commuterjoy** [comment]
https://www.youtube.com/watch?v=N6ZDAq3-_Rw

**Comment by matthew-andrews** [comment]
this is interesting, can we use the spoor pipeline for other system-level event logging?

**Comment by commuterjoy** [comment]
Yup, like change requests? What else?

If you Google 'unified log' there's lots of other examples of orgs doing this.

**Comment by matthew-andrews** [comment]
Is it possible to log things that happened in the past, eg. up to a day ago?

Yeah — releases, flag changes, etc

**Comment by commuterjoy** [comment]
Flags - great idea.

The webapp sends events from the past (eg, events that happened offline, sometimes days ago). As long as the event itself specifies when it happens then we can retrospectively add past events.

**Comment by matthew-andrews** [comment]
Great.  I have an idea that will immediately be both more comprehensive and simpler to implement than change requests — and require zero additional maintenance/additional work as we add new apps from that point on.

Download the releases / changes on a cron job from Heroku & AWS and post into spoor.

**Comment by matthew-andrews** [comment]
or maybe spoor can just understand heroku: https://devcenter.heroku.com/articles/deploy-hooks

**Comment by commuterjoy** [comment]
Ok, let's chat!

**Comment by commuterjoy** [comment]
http://ft-next-webhooks.herokuapp.com/

- [ ] heroku deploy
- [ ] circle ci
- [ ] pingdom
- [ ] github

**Comment by commuterjoy** [comment]
kinda done.
