### ISSUE TITLE
Negative time offsets

### ISSUE THREAD

**Issue by chrisbrownuk** [Financial-Times/spoor-enrichment#282]
We are generating time.offset values that are negative, which moves the time_stamp (time.now) into the future.

https://github.com/Financial-Times/spoor-enrichment/blob/9041cefd282446f30a4dc44f10f0caec49eae81a/server/transforms/time.js#L20

This should not happen, so checks need to be added.

**Comment by commuterjoy** [comment]
@chrisbrownuk Do you know why it's happening? Eg, are people sending local times (Spoor uses UTC) - is there a correlation with country codes?

**Comment by chrisbrownuk** [comment]
@commuterjoy It's the difference between the timestamp when the request is sent and queueTime timestamp in o-tracking.  Both times are milliseconds since midnight 1/1/70.  Not sure how this can be negative unless the clock was reset between the two times.

**Comment by commuterjoy** [comment]
ok, we are now rounding negative offsets to zero

**Comment by chrisbrownuk** [comment]
Great. Thanks

-- 

*Chris Brown*
TPO Web Analytics
Data Technology
Financial Times, One Southwark Bridge, London SE1 9HL

chris.brown@ft.com | +44 (0)207 873 4701

------------------------------

On 18 May 2016 at 15:38, Matt Chadburn <notifications@github.com> wrote:

> ok, we are now rounding negative offsets to zero
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/Financial-Times/spoor-enrichment/issues/282#issuecomment-220046913>
>

-- 

------------------------------

*This email was sent by a company owned by Financial Times Group Limited 
("FT Group <http://aboutus.ft.com/corporate-information/#axzz3rajCSIAt>"), 
registered office at Number One Southwark Bridge, London SE1 9HL.  
Registered in England and Wales with company number 879531. This e-mail may 
contain confidential information. If you are not the intended recipient, 
please notify the sender immediately, delete all copies and do not 
distribute it further.  It could also contain personal views which are not 
necessarily those of the FT Group.  We may monitor outgoing or 
incoming emails as permitted by law.*
