### ISSUE TITLE
Add a spoor id annotation

### ISSUE THREAD

**Issue by commuterjoy** [Financial-Times/spoor-enrichment#289]
Sometimes it's going to be found in the cookie, sometimes in the event body. The annotation would minimise the work consumers of the pipeline would need to do to find this data.

**Comment by Gkastrin** [comment]
Spoor Id is now available as an individual property in enriched messages.

**Comment by adambraimbridge** [comment]
(For my own records, because memory: https://github.com/Financial-Times/spoor-api/blob/master/server/middleware/anonymous-uuid.js#L20)
