### ISSUE TITLE
Collapse duplicate HTTP params

### ISSUE THREAD

**Issue by commuterjoy** [Financial-Times/spoor-enrichment#297]
`?foo=1&bar=2&foo=2` gets converted to `{ foo: [1, 2], bar: 2 }` at the moment, which is no good for the data warehouse or things like Keen.io

So @markstephens and I think we should remove duplicates.

There's no [authoritative spec](http://stackoverflow.com/questions/1746507/authoritative-position-of-duplicate-http-get-query-keys) for this, so I feel this is a valid approach.

**Comment by chrisbrownuk** [comment]
iJento tracking would only ever capture one value when there were duplicates, so that would be expected behaviour.

**Comment by markstephens** [comment]
👍

**Comment by markstephens** [comment]
Thanks Matt

I'll give it another test.



--
Mark Stephens
BI Solutions Architect
Financial Times Ltd ft.com
Email: mark.stephens@ft.com
Int Ext: 4251
Tel: 020 7873 4251

<https://www.facebook.com/financialtimes> <https://twitter.com/FT>
<http://www.linkedin.com/company/financial-times>
<https://plus.google.com/+FinancialTimes/posts>
<http://www.youtube.com/user/FinancialTimesVideos>

On 28 April 2016 at 10:28, Matt Chadburn <notifications@github.com> wrote:

> Closed #297
> <https://github.com/Financial-Times/spoor-enrichment/issues/297> via #299
> <https://github.com/Financial-Times/spoor-enrichment/pull/299>.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/Financial-Times/spoor-enrichment/issues/297#event-644048834>
>

-- 

------------------------------

*This email was sent by a company owned by Financial Times Group Limited 
("FT Group <http://aboutus.ft.com/corporate-information/#axzz3rajCSIAt>"), 
registered office at Number One Southwark Bridge, London SE1 9HL.  
Registered in England and Wales with company number 879531. This e-mail may 
contain confidential information. If you are not the intended recipient, 
please notify the sender immediately, delete all copies and do not 
distribute it further.  It could also contain personal views which are not 
necessarily those of the FT Group.  We may monitor outgoing or 
incoming emails as permitted by law.*
