### ISSUE TITLE
Subscriber/Premium cohort distinction is lost

### ISSUE THREAD

**Issue by georgecrawford** [Financial-Times/spoor-enrichment#301]
What's the reason for this? https://github.com/Financial-Times/spoor-enrichment/blob/master/server/utils/ft-cohorts.js#L4-L5

It's very valuable to us to know the difference between a `subscriber` and a `premium subscriber`. Were these categories joined simply because Next doesn't make a distinction?

**Comment by commuterjoy** [comment]
I we are fixing this properly in #110 via the membership user-status APIs

**Comment by georgecrawford** [comment]
Thanks for the update. As far as you know, what will be the future of the `actual cohort`, as per https://github.com/Financial-Times/spoor-enrichment/blob/master/server/transforms/user-api.js#L58 ? Can it return to the `registered, subscriber, premium, weekend` enum we know and love?

**Comment by commuterjoy** [comment]
@markstephens any objections?

**Comment by commuterjoy** [comment]
@Lucas-Gluchowski does Lantern depend on these properties?

**Comment by markstephens** [comment]
No objections, but need to let people know first, as a lot of stuff will be looking for "subscriber"
I'll send an email.

**Comment by commuterjoy** [comment]
@markstephens ok, thanks - yes, we need a better plan for API changes.

**Comment by Lucas-Gluchowski** [comment]
@commuterjoy Lantern is fine with adding new properties for cohort. We just get all values and display them, no IF ELSE statements.

**Comment by commuterjoy** [comment]
I'm using this approach, http://spoor-docs.herokuapp.com/annotations#products

```json
"products": {
    "productCodes": [
        "Tools",
        "P0",
        "P2"
    ],
    "productNames": [
        "registered",
        "premium"
    ],
    "cohorts": [
        "registered",
        "subscriber"
    ],
    "incumbent": "subscriber"
}
```

**Comment by georgecrawford** [comment]
Thanks Matt. Looks good.
