### ISSUE TITLE
Readme says I can set env vars for running locally but I found I had to create the files in my home directory for it to work

### ISSUE THREAD

**Issue by laurieboyes** [Financial-Times/spoor-enrichment#323]
Should the docs be updated to indicate that you need these files?:

.aws-access.spoor
.aws-secret.spoor
.aws-data-prod-debug-queue

**Comment by commuterjoy** [comment]
Thanks!

You can always set those env vars and run the app, but I've fixed the README in #328 

```
node --harmony-destructuring server/enrichment --region eu
```
