### ISSUE TITLE
Exclude AWS IP address ranges from IP address based transform

### ISSUE THREAD

**Issue by commuterjoy** [Financial-Times/spoor-enrichment#420]
http://docs.aws.amazon.com/general/latest/gr/aws-ip-ranges.html

It's pointless collecting data on server farms.

/cc @markstephens @chrisbrownuk agree?

**Comment by chrisbrownuk** [comment]
We do need to put something into the geo location fields so that the events can appear against something in downstream reports instead of null.

AWS do provide their region in this lookup.

**Comment by markstephens** [comment]
What's the reason behind this issue?
It's more work to filter them out than leave them..
It's probably handy to find someone scraping our sites...

**Comment by commuterjoy** [comment]
> What's the reason behind this issue?

I was looking at the MaxMind graph and saw we ask it for the IP address of all the email events, which are Heroku, so it's a few million (?) calls saved each day.

![www hostedgraphite-41](https://cloud.githubusercontent.com/assets/84996/17824216/99c78068-6658-11e6-9cfb-5c9f1e167b7c.png)

**Comment by commuterjoy** [comment]
> It's probably handy to find someone scraping our sites.

yeah, ok - i'll close this ticket. It was just a momentary idea.
