### ISSUE TITLE
Toggling enrichment flags in heroku only affects transforms that fetch()

### ISSUE THREAD

**Issue by adambraimbridge** [Financial-Times/spoor-enrichment#467]
The assumption is that adding a flag value in your transform will enable toggling on/off via heroku env vars. 

(e.g. https://github.com/Financial-Times/spoor-enrichment/blob/master/server/transforms/click.js#L117)

... but it looks like the flag's state is only consulted if the transform utilizes fetch():
https://github.com/Financial-Times/spoor-enrichment/blob/master/server/models/transform.js#L57

**Comment by commuterjoy** [comment]
oops - i should fix this.
