### ISSUE TITLE
Enrichment

### ISSUE THREAD

**Issue by commuterjoy** [Financial-Times/spoor-enrichment#5]
- [x] Move the demo consumers to the egest queue
- [x] Process the message body -> JSON
- [x] Statsd
- [x] Content API enrichment - Eg, if `page.id` is in the body hit CAPI

**Comment by richard-still-ft** [comment]
- [ ] H2 Enrichment - Set something like`h2: true` for browsers that [support HTTP2](https://en.wikipedia.org/wiki/HTTP/2#Browser_support).
