### ISSUE TITLE
Membership User Products API for cohorts

### ISSUE THREAD

**Issue by commuterjoy** [Financial-Times/spoor-enrichment#50]
Talk to DAM (rather than reading cohorts from cookies)

**Comment by markstephens** [comment]
See membership's API
https://sites.google.com/a/ft.com/technology/systems/membership/identity-and-access-management/02-sub-systems/user-product-service#TOC-Getting-Started

**Comment by commuterjoy** [comment]
I looked at DAM yesterday and it doesn't seem to contain much more than is in the cookies.
