### ISSUE TITLE
Content API v3 tests are failing

### ISSUE THREAD

**Issue by adambraimbridge** [Financial-Times/spoor-enrichment#527]
No code's changed (it seems), but since yesterday, builds have been failing on Content API v3 tests. 

At first I thought it was just my new branch, but a rebuild-without-cache of the master branch shows it's more serious than that.

![image](https://cloud.githubusercontent.com/assets/224547/21013212/11ee7fca-bd51-11e6-85e3-438ef6abd3a4.png)

**Comment by adambraimbridge** [comment]
https://circleci.com/gh/Financial-Times/spoor-enrichment/959

**Comment by adambraimbridge** [comment]
The tests are expecting this response:
```
{"ids":["xxxxxxxxx"]}
```
... but getting this response: 
```
{"docs":[{"_id":"xxxxxxxxx","_source":true}]}
```

Has something changed in https://next-elastic.ft.com/v3_api_v2/item/_mget ....?

**Comment by bjfletcher** [comment]
@adambraimbridge the `_mget` is standard Elastic Search API: https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-multi-get.html

which suggests that `{"docs":[{"_id":"xxxxxxxxx","_source":true}]}` is correct response.

The `{"ids":["xxxxxxxxx"]}` response sounds like something you'd get using github.com/financial-times/next-ft-api-client

But I'm no ES expert... best to check with Matt, Simon et al.

**Comment by commuterjoy** [comment]
hmm, I see the pipeline working ok - i.e. tests passing on my local host and the pipeline is attaching capi v3 data to each event

**Comment by adambraimbridge** [comment]
@bjfletcher Thanks. The tests were expecting the old incorrect response (`{"ids":["xxxxxxxxx"]}`),  and were passing tests until recently. 

@commuterjoy You might be running the fixed version that I merged into master about 15 mins ago. 

This bears further investigation. But for now it seems all is working as expected.

**Comment by adambraimbridge** [comment]
After looking through the tests with @i-like-robots I'm one part confused and two parts befuddled. 

We made a few initial changes to the test to get the "correct" error messages to display. (See: https://github.com/Financial-Times/spoor-enrichment/pull/529)

**Comment by adambraimbridge** [comment]
But even if we get the `/content-api-v3-next.spec.js` tests to pass, that doesn't explain why they started failing in the master branch without any code changes (just a rebuild-without-cache). 

So this issue still bears further work.

**Comment by commuterjoy** [comment]
`npm install next-ft-api-client@3.25.0` works

`npm install next-ft-api-client@3.26.0` fails

**Comment by commuterjoy** [comment]
https://github.com/Financial-Times/next-ft-api-client/commit/45bb976bd878bdabe616631da64e3f1dec6d2392
