### ISSUE TITLE
h2 annotations

### ISSUE THREAD

**Issue by commuterjoy** [Financial-Times/spoor-enrichment#55]
H2 Enrichment - Set something like `h2: true` for browsers that support HTTP2.

See beacon as a reference.

**Comment by commuterjoy** [comment]
https://raw.githubusercontent.com/Financial-Times/next-beacon/master/models/lib/connection.js

**Comment by richard-still-ft** [comment]
@tom-parker 

[ex-code.zip](https://github.com/Financial-Times/spoor-enrichment/files/86087/ex-code.zip)

**Comment by commuterjoy** [comment]
btw, I've asked @akilananb to pick this up over the next couple of weeks, so let him know if you are going to work on it.

**Comment by tom-parker** [comment]
Just FYI this work has been done in https://github.com/Financial-Times/spoor-enrichment/pull/232

**Comment by commuterjoy** [comment]
thanks @tom-parker !
