### ISSUE TITLE
`is-bot` enrichment (aka. device atlas)

### ISSUE THREAD

**Issue by georgecrawford** [Financial-Times/spoor-enrichment#61]
Probably requires both User-Agent and IP. Should include `Calypso Crawler`, a Google bot which recently started polling ft-app 30,000 times a day.

@markstephens do we have a list of patterns to match somewhere in the current iJento pipeline?

**Comment by markstephens** [comment]
Yes, it's in the plan, we're using a third party library for this - Device Atlas

I added a support ticket for that bot  the other day and they've added it to their definitions.

**Comment by georgecrawford** [comment]
Ref: https://jira.ft.com/browse/NGDA-83

**Comment by georgecrawford** [comment]
@markstephens, @commuterjoy - did you see https://deviceatlas.com/blog/deviceatlas-api-node-js ? Seems to make more sense to have this as a Node app.

**Comment by commuterjoy** [comment]
https://jira.ft.com/browse/NGDA-83 isn't accessible to Spoor at the moment :(

**Comment by commuterjoy** [comment]
> did you see https://deviceatlas.com/blog/deviceatlas-api-node-js

Good spot. Something cheap and in-memory is going to be quicker.

https://deviceatlas.com/getJSON - and we could automate loading daily updates.

**Comment by commuterjoy** [comment]
What we have today (a list of regex) is actually pretty effective - i.e. good enough.

**Comment by georgecrawford** [comment]
When you say we have a list, where do you mean?

**Comment by commuterjoy** [comment]
The ua parser library.

**Comment by markstephens** [comment]
* We're already using https://deviceatlas.com/getJSON to get a daily update.
* We have this app already written and running: http://ftweb38336-law1b-eu-d/
* A list of Regex isn't good enough, I know that DA use more than just the user agent to get their answer.
* This has to match what we have currently.

**Comment by georgecrawford** [comment]
@markstephens that's fine, but we'll have to manually set headers in the request to the DA app, as some data will come from JSON rather than HTTP headers. Can we get a list of what they use? UA, IP, ....?

**Comment by commuterjoy** [comment]
think this is done?

**Comment by markstephens** [comment]
Yep, done. 



> On 12 Oct 2015, at 22:37, Matt Chadburn <notifications@github.com> wrote:
> 
> Closed #61.
> 
> —
> Reply to this email directly or view it on GitHub.
> 

-- 

------------------------------
This email was sent by a company owned by Pearson plc, registered office at 
80 Strand, London WC2R 0RL.  Registered in England and Wales with company 
number 53723.
