### ISSUE TITLE
isStaff

### ISSUE THREAD

**Issue by commuterjoy** [Financial-Times/spoor-enrichment#80]
Capture if the user is staff or not.

**Comment by commuterjoy** [comment]
@markstephens yes, tom did this.

**Comment by markstephens** [comment]
Can I reopen this, as I have 2 points.
- We'll need to get the value from somewhere else in the future, as the cookie will disappear.
- If you are using cookies, in the `FT_User` cookie there is a `GROUPS` section and you can pick out the `FT Current Staff` group which should be better than the current method of email domain.

**Comment by commuterjoy** [comment]
being done as part of #110
