### ISSUE TITLE
Bucket referrers based on referrer hostname

### ISSUE THREAD

**Issue by markstephens** [Financial-Times/spoor-enrichment#81]
(Matches https://jira.ft.com/browse/NGDA-193)

For referrers, use the following logic to bucket them into higher level groupings: https://docs.google.com/a/ft.com/spreadsheets/d/101Qe-IZitindekrIolqJ_4DV7VwiI3wJirTdUiEjSyQ/edit?usp=sharing
From this sheet:
We want the value from the REFERRER_TYPE column.
The rules must be processed in order and exit on the first match

**Comment by commuterjoy** [comment]
@markstephens Who maintains this list - quite a few of the entries seem out of date or missing.

Eg,

- ftmandate.com (and a few other 301 to new domains).
- huffingtonpost.com is an aggregator?
- drudgereport.com is listed but not drudge.com
- netscape listed as a search engine but I'm sure it was bought by AOL about 10 years ago :)

I'm trying to think of a better solution to this than a keeping list of hard-coded URLs inside this application.

**Comment by markstephens** [comment]
@commuterjoy I'm creating a spreadsheet which will be bertha-ised, the Web Analytics team will own it and maintain it.

This is the bertha url: http://bertha.ig.ft.com/republish/publish/gss/1j1eiv5XkaqKSLCET7BWydydM7kX8nS-VLZKcFWmFB-s/referrers
- Order by `order`
- The `type` should help you decide what to match on.
- Match on the `matchstring`
- Return `bucket` on the first match

Do you have all the points you've raised above in a sheet or something similar, so we can update this new list?

**Comment by commuterjoy** [comment]
Excellent, this looks better. I wonder if we can ditch the regex? Scanning through a list of host names is very efficient. One concern is a badly written or broken regex is going to knock it out.

**Comment by commuterjoy** [comment]
Also, I think bucket should represent what the site is, and partner should be a flag. It avoids confusion about things like linkedin. 

Also, don't really need label.

Also, modified should be 'expiry date' after which point they stop working. Will keep things in order.

Also, remove `type` and replace with hostname or url as the property?

```
{
  order: 24,
  hostname: "linkedin.com",
  bucket: "social-network",
  isPartner: true,
  expiryDate: "2015-08-03T23:00:00.000Z"
},
```

**Comment by ironsidevsquincy** [comment]
If you prefix a column name with `special.`, bertha won't pick it up

**Comment by commuterjoy** [comment]
I'm going to do this as an external API, the the enrichment can simply the be a call to the API.

- https://spoor-website-type.herokuapp.com/http://www.drudgereport.com
- https://spoor-website-type.herokuapp.com/http://www.bbc.co.uk/news

I can foresee us wanting more information from referrers than just the it's _type._ Eg, maybe grabbing the open graph data, or collecting the user who tweeted a link (via the t.co domain), or even classifying the referrer's country.

TODO

 - [x] Make a simple API
 - [ ] Add spoor enrichment for the API

**Comment by markstephens** [comment]
Hi Matt

Thanks for actioning this, seems like a good solution. Gonna skip the Bertha solution in that case?

You mentioned more info, we've been thinking about a little enhancement for this already! At the moment we have _type_, we're thinking of adding a name too. e.g.

referrer | type | name
---------- | ----- | --------
t.co | social | twitter
twitter.com | social | twitter
facebook.com | social | facebook
bbc.co.uk/news | parter | BBC News

We almost have it with the `label` field, but maybe make it a bit more official and standardised.

What do you think?

**Comment by commuterjoy** [comment]
> Gonna skip the Bertha solution in that case?

@markstephens I like Bertha. I've just moved the logic to http://spoor-website-type.herokuapp.com/http://www.twitter.com, and then Spoor just hits this API.

i.e. https://github.com/Financial-Times/spoor-website-type/blob/master/server/controllers/lookup.js

Over time I'm conscious of spoor-enrichment becoming a spaghetti of lots of enrichments, so things like work nicely as APIs I think.

> We almost have it with the label field, but maybe make it a bit more official and standardised.

Great, if you can add any fields to Bertha spreadsheet and submit a ticket so I can update the enrichment.

The only field the enrichment needs at the moment is `matchstring` and `bucket`.

**Comment by markstephens** [comment]
Ok, so I've added a `name` to the spreadsheet - could you add it to the enrichment too?

**Comment by commuterjoy** [comment]
think this is done.

**Comment by markstephens** [comment]
yes.


--
Mark Stephens
BI Solutions Architect
Financial Times Ltd ft.com
Email: mark.stephens@ft.com
Int Ext: 4251
Tel: 020 7873 4251

<https://www.facebook.com/financialtimes> <https://twitter.com/FT>
<http://www.linkedin.com/company/financial-times>
<https://plus.google.com/+FinancialTimes/posts>
<http://www.youtube.com/user/FinancialTimesVideos>

On 4 January 2016 at 22:52, Matt Chadburn <notifications@github.com> wrote:

> think this is done.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Financial-Times/spoor-enrichment/issues/81#issuecomment-168837145>
> .
>

-- 

------------------------------

*This email was sent by a company owned by Financial Times Group Limited 
("FT Group <http://aboutus.ft.com/corporate-information/#axzz3rajCSIAt>"), 
registered office at Number One Southwark Bridge, London SE1 9HL.  
Registered in England and Wales with company number 879531. This e-mail may 
contain confidential information. If you are not the intended recipient, 
please notify the sender immediately, delete all copies and do not 
distribute it further.  It could also contain personal views which are not 
necessarily those of the FT Group.  We may monitor outgoing or 
incoming emails as permitted by law.*
