### ISSUE TITLE
Assign to "product" based on URL hostname

### ISSUE THREAD

**Issue by markstephens** [Financial-Times/spoor-enrichment#82]
(Matches https://jira.ft.com/browse/NGDA-192)

IF context.product exists then keep that value
Otherwise: Use the these mappings to assign a product based on the URL's host:  https://docs.google.com/a/ft.com/spreadsheets/d/1sJFtO04W-r8hHp5Tw95saLZbHcMJp7h4j4V3GvUqPyg/edit?usp=sharing

**Comment by commuterjoy** [comment]
Under what circumstance would a product using o-tracking not set this value? Do we really want to maintain a list of hostname mapping in this service?

**Comment by markstephens** [comment]
Yeah, I get your point.

o-tracking will send it, but it requires the product to set it in the init function. But, really, this came about after chatting to the membership team.

As someone visiting the subscription pages can come from any product, it doesn't make sense from them to set a hard-coded product, they will have to dynamically set the product based on where the user has come from.
Then we expanded the conversation a bit more and we thought it was better to have a central place for this map, rather than relying on products to implement different versions and keep up-to-date with the master list.

**Comment by commuterjoy** [comment]
Membership pages are a membership product, so the value should be 'membership' surely.

**Comment by commuterjoy** [comment]
Perhaps we just default to ft.com where it's not specified? Then if someone cares enough to override it they can spend 30 seconds doing that. Will save spoor playing whack-a-mole with new hostnames.

Also - I think the distinction between blogs and ft.com is an odd one. Blogs sit inside products. And, metaphysically, what _is_ a blog anyway. Is fastFT a blog? ;)

**Comment by markstephens** [comment]
Yeah, ok. I'll assign back to me for the moment and just double check.
