### ISSUE TITLE
Counted content flag

### ISSUE THREAD

**Issue by markstephens** [Financial-Times/spoor-enrichment#86]
Hi Matt

Can you add something like this as another enrichment. (Feel free to change my attempt at JS!!)

```js
function is_counted(message) {
  var hurdle = message.ingest._body.context.content.hurdle && message.ingest._body.context.content.hurdle !== "null";
  var barrier = message.ingest._body.context.content.barrier && message.ingest._body.context.content.barrier !== "null";
  var refresh = !!message.ingest._body.context.ad_refresh;
  var navigation = !!message.ingest._body.context.navigation;

  if (message.ingest._body.context.product) {
   switch (message.ingest._body.context.product) {

         // ft.com
         case "ft.com":
            var path_match = /.*(\/cms\/s\/[013]\/|\/fastft|\/presscuttings\/s\/3\/|\/the-a-list\/|\/brusselsblog\/|\/businessblog\/|\/david-allen-green\/|\/ftdata\/|\/material-world\/|\/off-message\/|\/the-world\/|\/westminster\/|\/lex-live\/).*/;

            if (path_match.test(message.egest.annotations.url.path) && !hurdle && !barrier && !refresh && !navigation) {
               return true;
            }
            break;

         // FT App
         case "FT App":
            var path_match = /.*(\/cms\/s\/[0-3]\/|\/the-a-list\/|\/fastft).*/;

            if (path_match.test(message.egest.annotations.url.path) && !hurdle && !barrier && !refresh && !navigation) {
               return true;
            }
            break;

         // m.ft.com
         case "m.ft.com":
            var path_match = /.*(\/cms\/|\/presscuttings\/s\/3\/|\/the-a-list\/).*/;

            if (path_match.test(message.egest.annotations.url.path) && !hurdle && !barrier && !refresh && !navigation) {
               return true;
            }
            break;

         // ePaper   
         case "epaper":
            if (message.ingest._body.context.counted === "1") {
               return true;
            }
            break;

         // Next
         case "next":
            if (["0", "1", "3"].indexOf(message.egest.annotations.content_v1.classification) > -1  && !hurdle && !barrier && !refresh && !navigation) {
               return true;
            }
            break;
      }
   }

   return false;
}

```

**Comment by commuterjoy** [comment]
So long as the app, ft.com and next send the uuid of the article with each o-tracking request we could consolidate this down to :-

```
isCounted = /0|1|3/.test(event.annotation('content_V1').classification);
```

/cc @georgecrawford 

>   var refresh = !!message.ingest._body.context.ad_refresh;

What's an 'ad refresh' ?

Also, we (next) are migrating traffic from m.ft.com *very* soon (august/sept) so probably don't need to worry too much about that.

**Comment by markstephens** [comment]
Yes, it can be consolidated down - still need to watch for barrier, hurdle and navigation.

Ad refresh was/is on ft.com, it was a thing that refreshed the whole page after X minutes, and we didn't want to count that again. I think it has disappeared now, but left it just in case.

**Comment by commuterjoy** [comment]
> it was a thing that refreshed the whole page after X minutes

ok - let's just say whoever puts a unannounced full page refresh on ft.com just to serve another advert gets whacked over the head with a cricket bat by me, and we'll ignore it for now.

**Comment by commuterjoy** [comment]
Thinking about barriers and hurdles (not sure of the difference) - but it would be better to have an event called category 'barrier' and an action called 'view' seems like a more sensible way to see this.

- page/view = someone has seen some content.
- barrier/view = someone has seen a barrier.

Not sure what navigation means.

**Comment by markstephens** [comment]
Yes, this calculation doesn't apply just to page views, there will be barrier view events and content consumed events too.

On ft.com this is how it works:
* User views the page, the underlying page knows a barrier will be shown, but it doesn't know which one yet (as the barrier is loaded with JS) - so with the page view there is a barrier=true flag.
* Then the barrier renders and we know more about the barrier, so an event is sent with barrier=premium
* The two are merged together later on to get the real answer.

On Web App:
* Same barrier logic as above.
* But, as users can swipe continuously through articles, we wait 5 seconds to send a navigational=false event - otherwise swiping through 8 articles (not even reading them) would use up a reg user's free allocation.

Next
* Don't know how it's working on Next, I assume the page knows when a barrier will be shown (as it has to hide the content), but I doubt a barrier parameter is being sent through.


To make all this simpler, we may decide to send a "content consumed" = true event when an article is consumed - as that's a positive statement, rather than trying to guess when it's not a barrier and not navigational - BUT, we need to recreate this calculation right now, as we don't have these content consumed events on any product (apart from epaper, which actually does) at the moment.

**Comment by commuterjoy** [comment]
Gone with a very simple definition for now #95.

Can reopen if we need more complexity added.
