### ISSUE TITLE
Ensure context.id is present enrichment

### ISSUE THREAD

**Issue by markstephens** [Financial-Times/spoor-enrichment#87]
Can you ensure context.id is present, and if not, gen a guid to go in there?

**Comment by commuterjoy** [comment]
Is this specific to o-tracking? So, we should check the `system.source === 'o-tracking'`

**Comment by markstephens** [comment]
No, it would apply to everything.

It allows me to create an event in the db, with child records for all the
key/values e.g.

event = video play
 | - key=video id, value=122345
 | - key=duration, value=10 seconds

event = email open
 | - key=campaign id, value=123456



--
Mark Stephens
BI Solutions Architect
Financial Times Ltd ft.com
Email: mark.stephens@ft.com
Int Ext: 4251
Tel: 020 7873 4251

<https://www.facebook.com/financialtimes> <https://twitter.com/FT>
<http://www.linkedin.com/company/financial-times>
<https://plus.google.com/+FinancialTimes/posts>
<http://www.youtube.com/user/FinancialTimesVideos>

On 7 August 2015 at 10:02, Matt Chadburn <notifications@github.com> wrote:

> Is this specific to o-tracking? So, we should check the system.source ===
> 'o-tracking'
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Financial-Times/spoor-enrichment/issues/87#issuecomment-128646621>
> .
>

-- 

------------------------------
This email was sent by a company owned by Pearson plc, registered office at 
80 Strand, London WC2R 0RL.  Registered in England and Wales with company 
number 53723.

**Comment by commuterjoy** [comment]
ah, ok - got it.
