### ISSUE TITLE
Document environment vars

### ISSUE THREAD

**Issue by commuterjoy** [Financial-Times/spoor-enrichment#98]
- [ ] Do something more sensible than keeping them in code and/or heroku env vars.
- [ ] Make sure it's written down in the README.

**Comment by matthew-andrews** [comment]
> more sensible than keeping them in code and/or heroku env vars.
could store them in ash ds/alan t's last pass thing?

**Comment by commuterjoy** [comment]
Yep. I really like the Next approach (an API to serve configuration), but don't want to tie Spoor to next in too many places.

Is the last pass thing an API?

**Comment by commuterjoy** [comment]
https://docs.google.com/document/d/1K8iwfCcnZaX53RfoNkXAcYeviksYmwYgoAbNkpGG6kU/edit

**Comment by commuterjoy** [comment]
Four options in order of preference ...

- Last Pass API
- https://aws.amazon.com/kms/
- https://vaultproject.io
- https://git.svc.ft.com:8080/projects/NEXTPRIVATE/repos/config-vars/browse - home made

**Comment by commuterjoy** [comment]
i think the simplest thing is just to reuse what we built for next.

**Comment by commuterjoy** [comment]
git.svc.ft.com:8080/projects/NEXTPRIVATE/repos/config-vars/browse

**Comment by matthew-andrews** [comment]
once the central last pass / config var api replacement tool thing is ready I will migrate all next stuff there so i think this is a good call ^^

**Comment by commuterjoy** [comment]
@akilananb did this. thanks !
